# Copyright (c) 2025, NVIDIA CORPORATION.
[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=64.0.0",
    "wheel"
]

[project]
name = "amd-dask-hip"
dynamic = ["version"]
description = "Utilities for Dask and HIP interactions"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Advanced Micro Devices, Inc." },
    { name = "NVIDIA Corporation" },
]
license = { text = "Apache-2.0 AND MIT" }
requires-python = ">=3.10"
dependencies = [
    "dask==2025.9.1",
    "distributed==2025.9.1",

    "hip-python==7.2.*",
    "hip-python-as-cuda==7.2.*",
    "numba-hip==0.1.6",
    "amdsmi==26.2.*",

    "click >=8.1",
    "numpy>=1.23,<3.0a0",
    "pandas>=1.3",
    "zict>=2.0.0",
    "rich"
]
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Database",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.scripts]
dask-cuda-worker = "dask_cuda.cli:worker"
dask-cuda-config = "dask_cuda.cli:config"

[project.entry-points.dask_cli]
cuda = "dask_cuda.cli:cuda"

[project.optional-dependencies]
docs = [
    "rocm-docs-core==1.27.0",
    "myst-parser",
    "sphinx-autoapi",
    "sphinx-copybutton",
]
test = [
    "pytest",
    "pytest-cov",
    "pytest-rerunfailures!=16.0.0",
    "pytest-timeout",
    "psutil",
    "pyarrow",
]
test_ucxx = [
    "amd-hipucxx==0.1.*",
    "amd-distributed-hipucxx==0.1.*",
]
test_hipdf = [
    "amd-dask-hipdf==3.0.*"
]

[project.urls]
Homepage = "https://github.com/ROCm-DS/dask-hip"
Documentation = "https://rocm.docs.amd.com/projects/dask-hip/en/latest/"
Source = "https://github.com/ROCm-DS/dask-hip"

[tool.coverage.run]
disable_warnings = [
    "include-ignored",
]
include = [
    "dask_cuda/*",
]
omit = [
    "dask_cuda/tests/*",
]

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
order_by_type = true
known_dask = [
    "dask",
    "distributed",
]
known_rapids = [
    "rmm",
    "cuml",
    "cugraph",
    "dask_cudf",
    "cudf",
    "ucp",
]
known_first_party = [
    "dask_cuda",
]
default_section = "THIRDPARTY"
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "DASK",
    "RAPIDS",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
skip = [
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".tox",
    ".venv",
    "build",
    "dist",
    "__init__.py",
]

[tool.pytest.ini_options]
filterwarnings = [
    "error::DeprecationWarning",
    "error::FutureWarning",
    # remove after https://github.com/rapidsai/dask-cuda/issues/1087 is closed
    "ignore:There is no current event loop:DeprecationWarning:tornado",
]

[tool.setuptools]
license-files = ["LICENSE", "NOTICE.txt"]

[tool.setuptools.dynamic]
version = {file = "dask_cuda/VERSION"}

[tool.setuptools.packages.find]
include = [
    "dask_cuda",
    "dask_cuda.*",
    "pynvml2amdsmi",
    "pynvml",
]
exclude = [
    "dask_cuda.benchmarks*",
    "dask_cuda.tests*",
]

[tool.pydistcheck]
select = [
    "distro-too-large-compressed",
]

# PyPI limit is 100 MiB, fail CI before we get too close to that
max_allowed_size_compressed = '75M'
