from _typeshed import Incomplete

is_device_object: Incomplete

def is_device_object_default(o): ...
def is_device_object_python_collection(seq): ...
def is_device_object_python_dict(seq): ...
def register_cudf(): ...
